# Coloumn Vlues to be fed in database.


rollNumber = "{}"
Gr_no = "{}"
firstName = "{}"
surName = "{}"
fathersName = "{}"
mothersName = "{}"
email = "{}@vit.edu"
isAadhar = "True"
aadhar = "123{}"
isPAN = "True"
PAN = "PAN{}"
isPassport = "True"
passport = "PA{}"
isIndian = "True"
nationality = "Indian"
mobileNumber = "{}"
permanantAddress = "perADD{}"
residentialAddress = "resADD{}"
tenthCGPA = "null"
twelfthCGPA = "null"
tenthGrade = 80.0
twelfthGrade = 85.0
firstSemCGPA = 9.1
secondSemCGPA = 8.4
thirdSemCGPA = 8.0
fourthSemCGPA = 8.6
fifthSemCGPA = 8.23
sixthSemCGPA = 8.76
seventhSemCGPA = "null"
eightthSemGCPA = "null"
isDiploma = "False"
diplomaMarks = "null"
isBacklog = "False"
numberOfBacklogs = 0
activeBacklog = 0
PassiveBacklog = 0
isYD = "False"
YDYears = 0
isEducationGap = "False"
educationGapYears = 0
currentBatch = 2022
state="state{}"
city="city{}"
pincode="{}"
branch_name="Branch{}"
college_name="VIT{}"
