# Coloumn Vlues to be fed in database.


rollNumber = "{}"
Gr_no = "{}"
firstName = "{}"
surName = "{}"
fathersName = "{}"
mothersName = "{}"
email = "{}@vit.edu"
isAadhar = "True"
aadhar = "{}"
isPAN = "True"
PAN = "{}"
isPassport = "True"
passport = "{}"
isIndian = "True"
nationality = "Indian"
mobileNumber = "{}"
permanantAddress = "{}"
residentialAddress = "{}"
tenthCGPA = "null"
twelfthCGPA = "null"
tenthGrade = "{}"
twelfthGrade = "{}"
firstSemCGPA = "{}"
secondSemCGPA = "{}"
thirdSemCGPA = "{}"
fourthSemCGPA = "{}"
fifthSemCGPA ="{}"
sixthSemCGPA = "{}"
seventhSemCGPA = "null"
eightthSemGCPA = "null"
isDiploma = "False"
diplomaMarks = "null"
isBacklog = "False"
numberOfBacklogs = 0
activeBacklog = 0
PassiveBacklog = 0
isYD = "False"
YDYears = 0
isEducationGap = "False"
educationGapYears = 0
currentBatch = 2022
state="state{}"
city="city{}"
pincode="{}"
branch_name="Branch{}"
college_name="VIT{}"
